foreground              #DADAE0
background              #151518

selection_foreground    #FFFFFF
selection_background    #3A3A44

cursor                  #C5C5D1
cursor_text_color       #151518

url_color               #8FAFD9

active_tab_foreground   #FFFFFF
active_tab_background   #2A2A32

inactive_tab_foreground #8C8C96
inactive_tab_background #1A1A1F

# black
color0 #1e1e22
color8 #000000

# red
color1 #d98787
color9 #d98787

# green
color2  #9EC3A5
color10 #9EC3A5

# yellow
color3  #D9C387
color11 #D9C387

# blue
color4  #8FAFD9
color12 #8FAFD9

# purple
color5  #B39AD9
color13 #B39AD9

# cyan
color6  #8FC9C3
color14 #8FC9C3

# white
color7  #E8E8EC
color15 #E8E8EC


