#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = hyprpaper
exec-once = nm-applet
exec-once = udiskie -t
exec-once = hyprctl setcursor MacTahoe 24
exec-once = powermode-indicator
exec-once = unclutter --timeout 5
exec-once = systemctl --user restart voxtype
